### ISSUE TITLE
HEAD request CORS issues when logging in

### ISSUE THREAD

**Issue by pheyvaer** [smessie/FormGenerator#7] opened 2023-02-07 15:59 UTC
After logging in, I get a blank page and there is the following error in the console

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://pieterheyvaert.com/#me. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

Looking at the network information, the error is coming from a HEAD request to my WebID.
I'm using FireFox Developer Edition 110.0b9 (64-bit). This error doesn't happen when using Chrome 109.0.5414.119.

I know that my server/pod doesn't set CORS headers for HEAD requests. but why should it? I've never seen HEAD request being mentioned in CORS discussions.

**Comment by smessie** [comment] 2023-02-08 11:34
- Does it work with https://pod.playground.solidlab.be in the same browser?
- Does it work in another browser?

The HEAD request is coming from following workaround, this is to support ESS, but this shouldn't affect CSS pods.
https://github.com/redpencilio/ember-solid/blob/experimental/ess-support/addon/utils/forking-store.js#L115-L122
It's weird that you're experiencing this bug as I cannot reproduce it myself.

**Comment by smessie** [comment] 2023-02-08 11:43
I'm getting the same CORS error with my id.inrupt.com pod, but this doesn't give me a blank page. Maybe something else is still causing that blank page.

**Comment by pheyvaer** [comment] 2023-02-08 11:56
- It works with the playground. That is using the latest stable release though so not v4. I also see that the playground sets CORS headers for HEAD. I can also do that of course. Weird, but ok. Nothing surprises me with CORS.
- Yes, it works in Chrome 109.0.5414.119.

**Comment by smessie** [comment] 2023-12-21 13:09
The internal architecture changed drastically, do you still experience this issue @pheyvaer ?

**Comment by smessie** [comment] 2024-01-10 21:57
Closing this issue for now. Feel free to reopen if you would still experience the same issue.

**Closed as completed by smessie** 2024-01-10 21:57 UTC
